### PR TITLE
OT208-97

### PR DESCRIPTION
**Pull request by EdwardDavys**
Metod delete in testimonial is changed
Delete class CategoryMapper
Test CategoryController

### CODE REVIEW

**Comment by Oriana10** [comment]
The test has no coverage

**Comment by Oriana10** [comment]
I ran the test in my environment and it indicates no coverage. Can anyone else please corroborate this?

**Review by juan1977lopez — COMMENTED** [review]
Por favor revisar comentarios!!!

**Comment by acamus79** [comment]
Hi, I made some changes in the branch so that the test coverage was 100%, I also removed the last mapper and factored the ObjetMapperUtils and maybe that's why it marks as many changes, since it modifies the import in all classes in which the mapper is used.

**Pull request merged**
